[versions]
micronaut="4.7.4"
micronaut-gradle="4.6.0"
kotlin="2.2.21"

[libraries]
kotlin-reflect = {module="org.jetbrains.kotlin:kotlin-reflect", version.ref="kotlin"}
kotlin-jdk8 = {module="org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref="kotlin"}

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "4.0.5"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref="kotlin"}
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref="kotlin"}
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref="kotlin"}
micronaut-application = { id = "io.micronaut.application", version.ref="micronaut-gradle"}
rewrite = { id = "org.openrewrite.rewrite", version = "7.19.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1"}

